name: dart_minimaldata
description: Following BIP62.3, this module validates that a script uses only minimal data pushes.
version: 1.0.0
homepage: https://github.com/dart-bitcoin-lib/dart_minimaldata
repository: https://github.com/dart-bitcoin-lib/dart_minimaldata
issue_tracker: https://github.com/dart-bitcoin-lib/dart_minimaldata/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  convert: ^3.0.1
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  dart_bitcoin_ops: ^1.0.2
  dart_bitcoin_pushdata: ^1.0.4
